FROM registry.access.redhat.com/ubi7/ubi-minimal:latest

ENV USER_UID=1001

ADD etcd /usr/local/bin/
ADD etcdctl /usr/local/bin/
RUN mkdir -p /var/etcd/
RUN chmod 700 /var/etcd
RUN chown 1001 /var/etcd
RUN mkdir -p /var/lib/etcd/
RUN chmod 700 /var/lib/etcd
RUN chown 1001 /var/lib/etcd

RUN mkdir -p ${HOME}
RUN chown ${USER_UID}:0 ${HOME}
RUN chmod ug+rwx ${HOME}
RUN chmod g+rw /etc/passwd

EXPOSE 2379 2380

USER ${USER_UID}

# Define default command.
CMD ["/usr/local/bin/etcd"]
