FROM registry.access.redhat.com/ubi7/ubi:latest

ENV USER_UID=1001
ENV USER_GID=1001

RUN groupadd -g ${USER_GID} -r etcd && useradd -r -u ${USER_UID} -g etcd etcd

LABEL name="PlanetScaleDB Operator etcd" \
      io.k8s.display-name="PlanetScaleDB Operator etcd" \
      maintainer="planetscaledboperator@planetscale.com" \
      vendor="PlanetScale, Inc." \
      version="3.3.20" \
      release="1" \
      summary="etcd container for PlanetScaleDB Operator" \
      description="etcd container for PlanetScaleDB Operator" \
      io.k8s.description="etcd container for PlanetScaleDB Operator" \
      distribution-scope="private" \
      url="https://planetscale.com"

ADD etcd /usr/local/bin/
ADD etcdctl /usr/local/bin/
RUN mkdir -p /licenses
COPY LICENSE /licenses
RUN mkdir -p /var/etcd/
RUN chmod 700 /var/etcd
RUN chown etcd:etcd /var/etcd
RUN mkdir -p /var/lib/etcd/
RUN chmod 700 /var/lib/etcd
RUN chown etcd:etcd /var/lib/etcd

RUN mkdir -p ${HOME}
RUN chown ${USER_UID}:0 ${HOME}
RUN chmod ug+rwx ${HOME}
RUN chmod g+rw /etc/passwd

EXPOSE 2379 2380

USER etcd

# Define default command.
CMD ["/usr/local/bin/etcd"]
